on:
  push:
  tags:
  # When a tag is created start the workflow.
  - 'v*'

name: Publish to Curse and Github.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout the repo.
        uses: actions/checkout@v2

      # https://github.com/actions/setup-java
      - name: Setup Java Dev Kit 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk
          architecture: x64

      - name: Fix file permissions.
        run: chmod a+x gradlew

      - name: Build using Gradle.
        id: build
        run: ./gradlew clean setupCurseForgeActions build

      - name: Push to CurseForge
        # Github action to use to build and upload to CurseForge
        uses: itsmeow/curseforge-upload@master
        with:
          # The API key for the mod on CurseForge.
          token: ${{secrets.CF_API_TOKEN}}
          # The CurseForge page ID.
          project_id: ${{steps.build.outputs.project_id}}
          # The game section on CurseForge we are uploading to.
          game_endpoint: minecraft
          # The output file location of the built mod.
          file_path: build/libs/${{steps.build.outputs.mod_id}}-${{steps.build.outputs.mod_version}}.jar
          # The link for the changelog.
          changelog: ${{steps.build.outputs.changelog}}
          # The display name for CurseForge.
          display_name: $${{steps.build.outputs.mod_name}} ${{steps.build.outputs.mod_version}}
          # Game version settings when uploading the mod.
          game_versions: ${{steps.build.outputs.curse_game_versions}}
          # The release type for the current built of the mod.
          release_type: ${{steps.build.outputs.release_type}}